name: Bug
description: Report a bug or other issue

labels: '👓 needs review'

body:
    -   type: markdown
        attributes:
            value: |
                Thanks for taking the time to fill out this bug report!

                ⚠️Review existing issues to see whether someone else has already reported your issue.
                📖 Please also read [CONTRIBUTING.md](https://laravel-lang.com/contributing.html).

    -   type: textarea
        id: environment
        attributes:
            label: Environment
            description: |
                Tip: Use the `composer info your/namespace` command to get information for Laravel Lang.
                Tip: Use the `composer info laravel/framework` command to get information for Laravel Framework.
                Tip: Use the `php -v` command to get information for PHP.
            value: |
                - Extended Lang Translations Template Version:
                - Laravel Version:
                - PHP Version:
        validations:
            required: true

    -   type: textarea
        id: description
        attributes:
            label: Issue description
            description: |
                Be as specific and detailed as possible to help us triaging your issue. Screenshots and/or animations can be very useful in helping to understand the issue you're facing.

                Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
                Tip: You can use https://www.screentogif.com to record animations and videos.
        validations:
            required: true

    -   type: textarea
        id: steps
        attributes:
            label: Steps to reproduce
            description: Take some time to try and reproduce the issue, then explain how to do so here.
        validations:
            required: true

    -   type: markdown
        attributes:
            value: |
                ❤️ Laravel Lang? Please consider supporting our collective: https://opencollective.com/laravel-lang
