name: Feature Proposal
description: Propose a new feature

labels:
    - '💪 feature request'

body:
    -   type: markdown
        attributes:
            value: |
                Thanks for taking the time to fill out this bug report!

                ⚠️Review existing issues to see whether someone else has already reported your issue.
                📖 Please also read [CONTRIBUTING.md](https://laravel-lang.com/contributing.html).

    -   type: textarea
        id: description
        attributes:
            label: Feature description
            description: |
                Think through your proposal and describe it clearly.

                Note that features are only added to the most recent version of Laravel Lang.
        validations:
            required: true

    -   type: textarea
        id: environment
        attributes:
            label: Environment
            description: |
                Tip: Use the `composer info your/namespace` command to get information for Laravel Lang.
                Tip: Use the `composer info laravel/framework` command to get information for Laravel Framework.
                Tip: Use the `php -v` command to get information for PHP.
            value: |
                - Extended Lang Translations Template Version:
                - Laravel Version:
                - PHP Version:
        validations:
            required: true

    -   type: markdown
        attributes:
            value: |
                ❤️ Laravel Lang? Please consider supporting our collective: https://opencollective.com/laravel-lang
