name: update

on:
    schedule:
        -   cron: 0 0 * * *
    push:
        branches:
            - main
    release:
        types:
            - released

permissions: write-all

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Git setup
                if: success()
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"

            -   name: Install dependencies
                run: composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Keys actualization
                id: keys
                if: success()
                run: |
                    IS_DIRTY=1

                    vendor/bin/lang sync

                    { git add . && git commit -a -m "Updating translations keys"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Update status of translations
                id: status
                if: success()
                run: |
                    IS_DIRTY=1

                    vendor/bin/lang status

                    { git add . && git commit -a -m "Updated status of translations"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Push changes
                uses: ad-m/github-push-action@master
                if: |
                    success() && (
                    steps.keys.outputs.is_dirty == 1 ||
                    steps.status.outputs.is_dirty == 1
                    )
                with:
                    github_token: ${{ secrets.COMPOSER_TOKEN }}
